server:
  port: 8099

value:
  name: sunzengjun

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: tk.mapper.model

spring:
    datasource:
        name: ${db.name}
        url: jdbc:mysql://${db.host}:${db.port}/${db.name}?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF8
        username: ${db.user}
        password: ${db.pwd}
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

db:
  host: 127.0.0.1  # 数据库地址
  port: 3306    # 数据库端口
  name: your_database_name  # database名
  user: user    # 用户名
  pwd: pwd   # 密码

logging:
    config: classpath:logback.xml
    path: log
